apiVersion: v1
kind: ConfigMap
metadata:
  name: shared-config
  namespace: default
data:
  NODE_ENV: "production"
  PORT: "8080"
  REDIS_URL: "redis://redis-cluster.default.svc.cluster.local:6379"
  RABBITMQ_URL: "amqp://guest:guest@rabbitmq.default.svc.cluster.local:5672"
  LEAD_SERVICE_URL: "http://lead-service.default.svc.cluster.local:5001"
  AI_SERVICE_URL: "http://ai-service.default.svc.cluster.local:5002"
